# Docker Compose v3.8 configuration for full-stack mood diary application
version: '3.8'

services:
  # MongoDB database service
  db:
    image: mongo:8.0.6  # Official MongoDB image with version pinning
    container_name: my-mood-diary-database  # Custom container naming
    environment:
      TZ: Pacific/Auckland  # Timezone configuration
      MONGO_INITDB_ROOT_USERNAME: 'admin'  # Root user credentials
      MONGO_INITDB_ROOT_PASSWORD: ABCabc-123
    volumes:
      - /root/container/mongodb/data:/data/db  # Persistent volume for data
      - ./backend/db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js  # Initialization script
    restart: always  # Automatic restart policy
    ports:
      - "27017:27017"  # Default MongoDB port mapping
    networks:
      - app-network  # Dedicated network for service discovery

  # Frontend service (Vue.js application)
  frontend:
    build:
      context: ./frontend  # Build context path
      dockerfile: Dockerfile  # Frontend Dockerfile location
    container_name: my-mood-diary-frontend
    ports:
      - "80:80"  # HTTP port mapping
    environment:
      - TZ: Pacific/Auckland
    restart: always
    networks:
      - app-network

  # Backend service (Spring Boot application)
  backend:
    build:
      context: ./backend  # Java project directory
      dockerfile: Dockerfile  # Backend Dockerfile location
    container_name: my-mood-diary-backend
    ports:
      - "8080:8080"  # Spring Boot default port
    environment:
      TZ: Pacific/Auckland
      DB_HOST: db  # MongoDB service name from docker-compose
      DB_USER: user  # Application database user
      DB_PORT: 27017
      DB_PASSWORD: ABCabc-123
      DB_NAME: my-mood-diary  # Target database name
    depends_on:
      - db  # Service dependency order
    restart: always
    networks:
      - app-network

# Network configuration for inter-container communication
networks:
  app-network:  # Custom bridge network
    driver: bridge  # Default network driver
